openapi: 3.0.3
info:
  title: Quotes API
  description: A basic API to scrape financial assets quotes from the boursorama website.
  version: 0.2.0
  license:
    name: GPL-3.0
servers:
  - url: http://localhost:8080
paths:
  /status:
    get:
      summary: Check the API availability
      operationId: checkStatus
      responses:
        '200':
          description: The API is up and running.
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'OK'
  /search:
    get:
      summary: Search for an asset
      operationId: searchAsset
      parameters:
      - name: q
        in: query
        description: Value of the requested asset.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Return the assets if found any.
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    symbol:
                      type: string
                    last_price:
                      type: string
        '400':
          description: Bad request
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /get/{symbol}:
    get:
      summary: Get the asset's quotes
      operationId: getQuotesBySymbol
      parameters:
      - name: symbol
        in: path
        description: The asset symbol.
        required: true
        schema:
          type: string
      - name: startDate
        in: query
        description: The date to start from.
        required: false
        schema:
          type: string
          default: 21/01/2021 (a month from now)
      - name: duration
        in: query
        description: Specify the duration from the start date.
        required: false
        schema:
          type: string
          default: 3M
          enum:
            - 1M
            - 2M
            - 3M
            - 4M
            - 5M
            - 6M
            - 7M
            - 8M
            - 9M
            - 10M
            - 11M
            - 1Y
            - 2Y
            - 3Y
      - name: period
        in: query
        description: Specify the number of days between each quote.
        required: false
        schema:
          type: string
          default: '1'
          enum:
            - '1'
            - '7'
            - '30'
            - '365'
      responses:
        '200':
          description: Return the quotes with dates.
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    price:
                      type: string
        '400':
          description: Bad request
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
