name: Release

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See https://github.com/goreleaser/goreleaser-action#workflow
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BFINANCE_GO_GITHUB_TOKEN }}
